services:
  wormhole-base:
    &base-service
      build: .
      privileged: true
      cap_add:
        - SYS_ADMIN
      devices:
        - '/dev/fuse'
      volumes:
        - ./shared_mnt:/usr/src/wormhole/virtual:rwx
      ports:
        - "8080"

  wormhole1:
    <<: *base-service
    container_name: w1
    command: "./wormhole-service 127.0.0.1:8081 127.0.0.2:8081 127.0.0.3:8081 /usr/src/wormhole/virtual >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt1:/usr/src/wormhole/virtual:rwx

  wormhole2:
    <<: *base-service
    container_name: w2
    command: "./wormhole-service 127.0.0.2:8081 127.0.0.1:8081 127.0.0.3:8081 /usr/src/wormhole/virtual >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt2:/usr/src/wormhole/virtual:rwx

  wormhole3:
    <<: *base-service
    container_name: w3
    command: "./wormhole-service 127.0.0.3:8081 127.0.0.2:8081 127.0.0.1:8081 /usr/src/wormhole/virtual >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt3:/usr/src/wormhole/virtual:rwx