services:
  wormhole-base:
    &base-service
    user: "root:root"
    build: .
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_OVERRIDE
      - SYS_PTRACE
    devices:
      - '/dev/fuse'
    volumes:
      - ./shared_mnt:/usr/src/wormhole/virtual:rwx,Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stdin_open: true
    tty: true
    networks:
      - wormhole-net
    environment:
      - VIRTUAL_FS_ROOT=/usr/src/wormhole/virtual
      - RUST_BACKTRACE=1
      - FUSE_GROUP_ID=root
      - RUST_LOG=debug
      - SERVICE_ADDRESS=0.0.0.0:8081

  wormhole1:
    <<: *base-service
    container_name: w1
    ports:
      - "8081:8081"
    networks:
      - wormhole-net

  wormhole2:
    <<: *base-service
    container_name: w2
    ports:
      - "8082:8081"
    networks:
      - wormhole-net
    depends_on:
      - wormhole1

networks:
  wormhole-net:
    driver: bridge