services:
  whone:
    build:
      context: .
      network: host
    network_mode: "host"
    devices:
      - '/dev/fuse'
    cap_add:
      - "SYS_ADMIN"
    privileged: true
    volumes:
      - ./dockertest:/wormhole:rwx
    environment:
      RUST_LOG: "wormhole=trace"

  whtwo:
    build:
      context: .
      network: host
    network_mode: "host"
    devices:
      - '/dev/fuse'
    cap_add:
      - "SYS_ADMIN"
    privileged: true
    volumes:
      - ./dockertest:/wormhole:rwx
    environment:
      RUST_LOG: "wormhole=trace"
