services:
  wormhole-base:
    &base-service
      build: .
      privileged: true
      cap_add:
        - SYS_ADMIN
      devices:
        - '/dev/fuse'
      stdin_open: true
      tty: true

  wormhole1:
    <<: *base-service
    container_name: w1
    ports:
      - "8081:8081"
    command: "./wormhole-service 0.0.0.0:8081 localhost:8082 localhost:8083 /usr/src/wormhole/virtual >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt1:/usr/src/wormhole/virtual:rwx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  wormhole2:
    <<: *base-service
    container_name: w2
    ports:
      - "8082:8081"
    command: "./wormhole-service 0.0.0.0:8082 localhost:8081 localhost:8083 /usr/src/wormhole/virtual >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt2:/usr/src/wormhole/virtual:rwx
    depends_on:
      - wormhole1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  wormhole3:
    <<: *base-service
    container_name: w3
    ports:
      - "8083:8081"
    command: "./wormhole-service 0.0.0.0:8083 localhost:8081 localhost:8082 /usr/src/wormhole/virtual >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt3:/usr/src/wormhole/virtual:rwx
    depends_on:
      - wormhole2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s