services:
  wormhole1:
    build: .
    environment:
      - RUST_LOG=info
      - WH_ADDRESS=127.0.01:8080
      - WH_PEERS=ws://127.0.02:8080, ws://127.0.0.3:8080
      - WH_MOUNT_POINT=/mnt/virtual1
    ports:
      - "8081:8080"
    privileged: true
    cap_add:
    - SYS_ADMIN
    devices:
      - '/dev/fuse'
    volumes:
      - type: bind
        source: ./shared_mnt1
        target: /mnt/virtual1
        bind:
          propagation: shared
  wormhole2:
    build: .
    environment:
      - RUST_LOG=info
      - WH_ADDRESS=127.0.02:8080
      - WH_PEERS=ws://127.0.01:8080, ws://127.0.0.3:8080
      - WH_MOUNT_POINT=/mnt/virtual2
    ports:
      - "8082:8080"
    privileged: true
    cap_add:
    - SYS_ADMIN
    devices:
      - '/dev/fuse'
    volumes:
      - type: bind
        source: ./shared_mnt2
        target: /mnt/virtual2
        bind:
          propagation: shared
  wormhole3:
    build: .
    environment:
      - RUST_LOG=info
      - WH_ADDRESS=127.0.03:8080
      - WH_PEERS=ws://127.0.02:8080, ws://127.0.0.1:8080
      - WH_MOUNT_POINT=/mnt/virtual3
    ports:
      - "8083:8080"
    privileged: true
    cap_add:
    - SYS_ADMIN
    devices:
      - '/dev/fuse'
    volumes:
      - type: bind
        source: ./shared_mnt3
        target: /mnt/virtual3
        bind:
          propagation: shared
