services:
  whone:
    build:
      context: .
    post_start:
      - command: sh -c "sleep 1 &&
                        mkdir whfolder &&
                        wormhole new pod1 -p 5000 -m whfolder"
    devices:
      - '/dev/fuse'
    cap_add:
      - "SYS_ADMIN"
    environment:
      RUST_LOG: "wormhole=trace"

  whtwo:
    build:
      context: .
    post_start:
      - command: sh -c "sleep 2 &&
                        mkdir whfolder &&
                        wormhole new pod2 -p 5000 -m whfolder -u whone:5000"
    devices:
      - '/dev/fuse'
    cap_add:
      - "SYS_ADMIN"
    environment:
      RUST_LOG: "wormhole=trace"

  whthree:
    build:
      context: .
    post_start:
      - command: sh -c "sleep 3 &&
                        mkdir whfolder &&
                        wormhole new pod3 -p 5000 -m whfolder -u whtwo:5000"
    devices:
      - '/dev/fuse'
    cap_add:
      - "SYS_ADMIN"
    environment:
      RUST_LOG: "wormhole=trace"
