services:
  wormhole-base:
    &base-service
    user: "root:root"
    build: .
    privileged: true
    security_opt:
      - seccomp:unconfined  # Désactive SELinux
    cap_add:
      - SYS_ADMIN
      - DAC_OVERRIDE
      - SYS_PTRACE
    devices:
      - '/dev/fuse'
    volumes:
      - ./shared_mnt:/usr/src/wormhole/virtual:rwx,Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - wormhole-net
    stdin_open: true
    tty: true
    environment:
      - VIRTUAL_FS_ROOT=/usr/src/wormhole/virtual
      - RUST_BACKTRACE=1
      - FUSE_GROUP_ID=root
      - RUST_LOG=debug
    command: "./wormhole-service"

  wormhole1:
    <<: *base-service
    container_name: w1
    volumes:
      - ./shared_mnt1:/usr/src/wormhole/virtual:rwx,Z
    expose:
      - "8081"  # Accessible par les autres conteneurs via le réseau Docker
    ports:
      - "192.168.1.100:8081:8081"  # Exemple : écoute sur l'IP 192.168.1.100 de l'hôte
    command: "./wormhole-service 0.0.0.0:8081"

  wormhole2:
    <<: *base-service
    container_name: w2
    volumes:
      - ./shared_mnt2:/usr/src/wormhole/virtual:rwx,Z
    expose:
      - "8081"  # Accessible par les autres conteneurs via le réseau Docker
    ports:
      - "192.168.1.100:8082:8081"  # Exemple : écoute sur l'IP 192.168.1.100 de l'hôte
    command: "./wormhole-service 0.0.0.0:8082"

networks:
  wormhole-net:
    driver: bridge