services:
  wormhole-base:
    &base-service
    build: .
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - '/dev/fuse'
    volumes:
      - ./shared_mnt:/usr/src/wormhole/virtual:rwx
    stdin_open: true
    tty: true
    networks:
      - wormhole-net

  wormhole1:
    <<: *base-service
    container_name: w1
    networks:
      - wormhole-net
    command: "./wormhole-service 0.0.0.0:8082 wormhole2:8082 wormhole3:8082 /usr/src/wormhole/virtual >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt1:/usr/src/wormhole/virtual:rwx

  wormhole2:
    <<: *base-service
    container_name: w2
    networks:
      - wormhole-net
    command: "./wormhole-service 0.0.0.0:8082 wormhole1:8082 wormhole3:8082 /usr/src/wormhole/virtual >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt2:/usr/src/wormhole/virtual:rwx

  wormhole3:
    <<: *base-service
    container_name: w3
    networks:
      - wormhole-net
    command: "./wormhole-service 0.0.0.0:8082 wormhole1:8082 wormhole2:8082 /usr/src/wormhole/virtual >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt3:/usr/src/wormhole/virtual:rwx

networks:
  wormhole-net:
    driver: bridge