services:
  wormhole-base:
    &base-service
    user: "root:root"
    build: .
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_OVERRIDE
      - SYS_PTRACE
    devices:
      - '/dev/fuse'
    volumes:
      - ./shared_mnt:/usr/src/wormhole/virtual:rwx,Z
    stdin_open: true
    tty: true
    networks:
      - wormhole-net
    environment:
      - VIRTUAL_FS_ROOT=/usr/src/wormhole/virtual
      - RUST_BACKTRACE=1
      - FUSE_GROUP_ID=root

  wormhole1:
    <<: *base-service
    container_name: w1
    networks:
      - wormhole-net
    command: "./wormhole-service >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt1:/usr/src/wormhole/virtual:rwx,Z
    ports:
      - "8081:8081"

  wormhole2:
    <<: *base-service
    container_name: w2
    networks:
      - wormhole-net
    command: "./wormhole-service >> /var/log/wormhole.log 2>&1"
    volumes:
      - ./shared_mnt2:/usr/src/wormhole/virtual:rwx,Z
    ports:
      - "8082:8081"
    depends_on:
      - wormhole1

networks:
  wormhole-net:
    driver: bridge