name: Mirror Repository

on:
  push:
    branches:
      - main

name: Check PR Source Branch

on:
  pull_request:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is from dev branch
    run: |
      if [ "${{ github.head_ref }}" != "dev" ]; then
        echo "Pull requests to main must come from the dev branch."
        exit 1
      fi
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: Agartha-Software/Wormhole
        token: ${{ secrets.MIRROR_REPO_TOKEN }}

    - name: Push to mirror repository
      run: |
        git remote add mirror https://github.com/EpitechPromo2026/G-EIP-700-PAR-7-1-eip-axel.denis.git
        git push mirror main --force
