name: NIX CI Pipeline Rust

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NIX_PATH: nixpkgs=channel:nixos-25.05

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Nix store
        uses: actions/cache@v4
        id: nix-cache
        with:
          path: |
            /nix/store
            /nix/var/nix/profiles
          key: nix-store-${{ runner.os }}-${{ env.NIX_PATH }}-${{ hashFiles('flake.lock') }}-${{ hashFiles('flake.nix') }}
          restore-keys: |
            nix-store-${{ runner.os }}-${{ env.NIX_PATH }}-

      - name: Set up Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: ${{ env.NIX_PATH }}
        extra_nix_config: |
            experimental-features = nix-command flakes
            build-users-group = nixbld


      - name: Enter Nix devShell and build
        run: |
          nix develop --command cargo build

      - name: Run tests in Nix shell
        run: |
          nix develop --command cargo test -- --nocapture
