name: CI Pipeline Rust

# Implementation of the workflow on push or pull request
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    # Specify on which type of machine to run the job
    runs-on: ubuntu-latest

    # Configuring steps
    steps:
      # Step 1: Clone the deposit
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 : Install Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Step 3: Complie the project
      - name: Build the project
        run: cargo build --verbose

      # Step 4: Run the tests
      - name: Run tests
        run: cargo test --verbose
