name: Mirror Repository

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/G-EIP-700-PAR-7-1-eip-axel.denis.git

on:
  pull_request:
    branches: ["main"]

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if this is the destination repository
        id: check_mirror
        run: |
          if [[ "${{ github.repository }}" == "EpitechPromo2026/G-EIP-700-PAR-7-1-eip-axel.denis" ]]; then
            echo "This is the destination repository. Skipping mirroring."
            echo "::set-output name=skip_mirror::true"
          else
            echo "::set-output name=skip_mirror::false"
          fi
      - name: Mirror repository
        if: steps.check_mirror.outputs.skip_mirror == 'false'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}