name: Release Minor

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.0.0'


jobs:
  build:
    name: Release Minor
    permissions:
      contents: write
      # write permission is required for autolabeler
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          cargo build
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-minor.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}