name: Release Minor

on:
  workflow_dispatch:

jobs:
  build:
    name: Release Minor
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build project
        run: |
          cargo build
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-minor.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}